FROM dvmarques/openjdk-17-jdk-alpine-with-timezone
WORKDIR C:\Users\NANDITHAPRABU\Downloads\7thSem\devOps-MLops-lab\dockerLab
COPY ./dockerLab dockerLab
RUN javac HelloWorld.java
RUN java HelloWorld 
# CMD["java", "HelloWorld"] -- also works